#!/bin/bash

# rm -rf ${HOME}/Arduino

mkdir -p ${HOME}/Arduino/libraries

cd ${HOME}/Arduino/libraries
git clone https://github.com/witnessmenow/Universal-Arduino-Telegram-Bot
git clone https://github.com/bblanchon/ArduinoJson.git
git clone https://github.com/marcoschwartz/LiquidCrystal_I2C
git clone https://github.com/adafruit/DHT-sensor-library
git clone https://github.com/gamgine/HCSR04-ultrasonic-sensor-lib
git clone https://github.com/adafruit/Adafruit_Sensor
git clone https://github.com/arduino-libraries/NTPClient
git clone https://github.com/acrobotic/Ai_Ardulib_SSD1306
git clone https://github.com/Behooz-Sirouszad/ESP8266_Gmail_Sender_sirouszad
git clone https://github.com/adafruit/MAX31850_OneWire
git clone https://github.com/adafruit/MAX31850_DallasTemp

