#!/bin/bash

# rm -rf ${HOME}/Arduino

mkdir -p ${HOME}/Arduino/hardware/esp8266com
mkdir -p ${HOME}/Arduino/libraries

cd ${HOME}/Arduino/hardware/esp8266com
git clone https://github.com/esp8266/Arduino.git esp8266
cd esp8266/tools
python get.py

